version: "3"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/docker.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=database
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres