# pull official base image
FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./

# install missing dependency    
RUN npm install chalk

# add app
COPY . ./

# start app
CMD ["npm", "start"]